source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.ms.netease.com/commonlibraryios/podspec.git'
source 'https://git.ms.netease.com/preciousmetals/ldpmspecs.git'

target 'LDAPMMonitor' do
    pod 'FBRetainCycleDetector', '~> 0.1.4'
    pod 'Reachability'
end

